### ISSUE TITLE
'fiXed eVErYtHInG'

### ISSUE THREAD

**Issue by StupidRepo** [monkxy/blooket-hacks#104]
More like - 'Encoded/obfuscated all working hacks and new ones'. Why have you done this? All the ones you didn't add worked fine and didn't need obfuscating? Is it because your embarrassed to show us your ugly code? Or is it because you didn't really 'fix everything', because nothing was broken?

**Comment by monkxy** [comment]
When I pushed the code the other day multiple people said it didn't work so I reverted the change, the code isn't ugly and I'm not embarrassed to show it I was fixing an error.

**Comment by StupidRepo** [comment]
> When I pushed the code the other day multiple people said it didn't work so I reverted the change, the code isn't ugly and I'm not embarrassed to show it I was fixing an error.

Then why have you encoded all the scripts?

**Comment by monkxy** [comment]
because those were the working versions, the unobfuscated code did not work, so i reverted the change

**Comment by monkxy** [comment]
why is this a big deal to you?

**Comment by StupidRepo** [comment]
So you stole the scripts from a different repo and claimed them as your own?

**Comment by monkxy** [comment]
no?
