### ISSUE TITLE
That’s it

### ISSUE THREAD

**Issue by JaydenTD500** [monkxy/blooket-hacks#106]
You keep saying i steal your scripts, but you literally stole the add tokens script from https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Add%20Rewards.js.
When it was deobfuscated, it was the exact some as the user therealglixzzy’s hacks but just modified using https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Add%20Rewards.js. When i confronted you with an issue, the issue was deleted.

**Comment by JaydenTD500** [comment]
Ok

**Comment by intertransfer** [comment]
balls

**Comment by monkxy** [comment]
> You keep saying i steal your scripts, but you literally stole the add tokens script from https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Add%20Rewards.js.
> 
> When it was deobfuscated, it was the exact some as the user therealglixzzy’s hacks but just modified using https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Add%20Rewards.js. When i confronted you with an issue, the issue was deleted.

ironic when you use all of this code i have on your page it says my legal name, using the gliz code is fair use, using my code is not.
